[package]
name = "rust-arm-barebone"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
cfg-if = "1.0.0"
bitfield = "0.14.0"

[features]
#default = ["boot_from_flash"]
boot_from_flash = []